on:
  pull_request_target:
    types: [labeled]


name: "Deploy PR for review"

jobs:
  deploy:
    if: ${{ github.event.label.name == 'HTML available' }}
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v7
        with:
          pr: ${{github.event.pull_request.number}}
          workflow: ci.yml
          workflow_conclusion: success
          name: 'html'
          path: _out
          allow_forks: true

      # deploy-alias computes a URL component for the PR preview. This
      # is so we can have a stable name to use for feedback on draft
      # material.
      - id: deploy-alias
        uses: actions/github-script@v7
        name: Compute Alias
        with:
          script: |
            if (process.env.PR) {
                return `pr-${process.env.PR}`
            } else {
                return 'deploy-preview-main';
            }
        env:
          PR: ${{ github.event.number }}

      - name: Deploy current draft
        id: deploy-draft
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: _out/html-multi
          production-branch: main
          production-deploy: false
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: |
            ${{ format('pr#{0}: {1}', github.event.number, github.event.pull_request.title) }}
          alias: ${{ steps.deploy-alias.outputs.result }}
          enable-commit-comment: false
          enable-pull-request-comment: false
          github-deployment-environment: |
            ${{ github.event_name == 'pull_request' && format('lean-ref-pr-#{0}', github.event.number) || 'lean-ref' }}
          github-deployment-description: |
            Draft without proofreading info
          fails-without-credentials: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: "32e0f63e-7a18-4bf9-87f4-713650c7db70"

      # When pushing to `main` or a PR branch, deploy it with proofreading info as well
      - name: Deploy with proofreading info (draft mode, for PRs)
        id: deploy-draft-proofreading
        uses: nwtgck/actions-netlify@v2.0
        if:
          github.event_name == 'pull_request'
        with:
          publish-dir: _out/draft/html-multi
          production-branch: main
          production-deploy: false
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: |
            ${{ format('pr#{0} proofreading: {1}', github.event.number, github.event.pull_request.title) }}
          alias: draft-${{ steps.deploy-alias.outputs.result }}
          enable-commit-comment: false
          enable-pull-request-comment: false
          github-deployment-environment: |
            ${{ format('lean-ref-pr-draft-#{0}', github.event.number) }}
          github-deployment-description: |
            Draft with proofreading info
          fails-without-credentials: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: "32e0f63e-7a18-4bf9-87f4-713650c7db70"
    
